2022-10-04 06:14:56 =ERROR REPORT====
Error in process <0.23407.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.Mix.Error',message => <<"Can't continue due to errors on dependencies">>,mix => 1},[{'Elixir.Mix',raise,2,[{file,"lib/mix.ex"},{line,513}]},{'Elixir.Mix.Tasks.Deps.Loadpaths',run,1,[{file,"lib/mix/tasks/deps.loadpaths.ex"},{line,43}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.Mix.Tasks.Loadpaths',run,1,[{file,"lib/mix/tasks/loadpaths.ex"},{line,41}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.Mix.Tasks.Compile',run,1,[{file,"lib/mix/tasks/compile.ex"},{line,126}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.ElixirLS.LanguageServer.Build',compile,0,[{file,"lib/language_server/build.ex"},{line,139}]}]}
2022-10-04 06:15:14 =ERROR REPORT====
Error in process <0.23479.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.Mix.Error',message => <<"Can't continue due to errors on dependencies">>,mix => 1},[{'Elixir.Mix',raise,2,[{file,"lib/mix.ex"},{line,513}]},{'Elixir.Mix.Tasks.Deps.Loadpaths',run,1,[{file,"lib/mix/tasks/deps.loadpaths.ex"},{line,43}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.Mix.Tasks.Loadpaths',run,1,[{file,"lib/mix/tasks/loadpaths.ex"},{line,41}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.Mix.Tasks.Compile',run,1,[{file,"lib/mix/tasks/compile.ex"},{line,126}]},{'Elixir.Mix.Task','-run_task/4-fun-5-',3,[{file,"lib/mix/task.ex"},{line,421}]},{'Elixir.ElixirLS.LanguageServer.Build',compile,0,[{file,"lib/language_server/build.ex"},{line,139}]}]}
2022-10-04 06:16:46 =ERROR REPORT====
Error in process <0.24160.0> with exit value:
{noproc,[{erlang,link,[<0.24039.0>],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Module.ParallelChecker','-spawn/3-fun-0-',5,[{file,"lib/module/parallel_checker.ex"},{line,56}]}]}
2022-10-04 06:16:46 =ERROR REPORT====
Error in process <0.24161.0> with exit value:
{noproc,[{erlang,link,[<0.24039.0>],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Module.ParallelChecker','-spawn/3-fun-0-',5,[{file,"lib/module/parallel_checker.ex"},{line,56}]}]}
